backend:
    name: git-gateway
    branch: master

publish_mode: editorial_workflow

media_folder: src/images
public_folder: /images

collections:
    - name: Home
      label: Home
      folder: src/data/home
      fields:
          - { name: path, label: Path }
          - { name: date, label: Date, widget: datetime }
          - { name: title, label: Title }
          - { name: body, label: Body, widget: markdown }

    - name: Over-ons
      label: Over-ons
      folder: src/data/over-ons
      fields:
          - { name: path, label: Path }
          - { name: date, label: Date, widget: datetime }
          - { name: title, label: Title }
          - { name: body, label: Body, widget: markdown }

    - name: Tarieven
      label: Tarieven
      folder: src/data/tarieven
      fields:
          - { name: path, label: Path }
          - { name: date, label: Date, widget: datetime }
          - { name: title, label: Title }
          - { name: body, label: Body, widget: markdown }

    - name: Contact
      label: Contact
      folder: src/data/contact
      fields:
          - { name: path, label: Path }
          - { name: date, label: Date, widget: datetime }
          - { name: title, label: Title }
          - { name: body, label: Body, widget: markdown }

    - name: Cursus
      label: Cursus
      folder: src/data/cursus
      create: true
      fields:
          - { name: path, label: Path }
          - { name: date, label: Date, widget: datetime }
          - { name: title, label: Title }
          - { name: body, label: Body, widget: markdown }
