backend:
    name: git-gateway
    branch: master

publish_mode: editorial_workflow

media_folder: src/images
public_folder: /images

collections:
    - name: "home"
    label: "Home"
    folder: "src/data/home"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}

    - name: Over-ons
      label: Over-ons
      folder: src/data/over-ons
      fields:
          - { name: path, label: Path }
          - { name: date, label: Date, widget: datetime }
          - { name: title, label: Title }
          - { name: body, label: Body, widget: markdown }

    - name: Tarieven
      label: Tarieven
      folder: src/data/tarieven
      fields:
          - { name: path, label: Path }
          - { name: date, label: Date, widget: datetime }
          - { name: title, label: Title }
          - { name: body, label: Body, widget: markdown }

    - name: Contact
      label: Contact
      folder: src/data/contact
      fields:
          - { name: path, label: Path }
          - { name: date, label: Date, widget: datetime }
          - { name: title, label: Title }
          - { name: body, label: Body, widget: markdown }

    - name: Cursus
      label: Cursus
      folder: src/data/cursus
      create: true
      fields:
          - { name: path, label: Path }
          - { name: date, label: Date, widget: datetime }
          - { name: title, label: Title }
          - { name: body, label: Body, widget: markdown }
